[package]
name = "thread2"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo-embed = "1.0.1"
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
stm32f4xx-hal = { version = "0.22.1", features = ["stm32f407"] }